[project]
name = "Datamart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.0",
    "duckdb>=1.4.3",
    "duckdb-engine>=0.15.0",
    "ipykernel>=7.1.0",
    "kagglehub>=0.4.0",
    "matplotlib>=3.10.8",
    "notebook>=7.5.2",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.0",
]
